# Generated by Django 5.1.6 on 2025-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvadd',
            name='age',
        ),
        migrations.AddField(
            model_name='cvadd',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='last_increment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='last_promotion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performanseappraisal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
