# Generated by Django 5.1.6 on 2025-05-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_remove_cvadd_age_cvadd_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvadd',
            old_name='date_of_birth',
            new_name='age',
        ),
    ]
